# -p - public folder creation

name: Test Automation Framework 

on:
  schedule:
   - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Execute Test Automation with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Test Logs
        path: logs/

    - name: Upload Test screenshots as artifacts
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: screenshots
        path: screenshots/

    - name: Upload HTML Report as Artifact
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: html-report
        path: report.html

    - name: Test Execution Status
      if: always()
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages Folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports/
        cp -R screenshots/public/extent-reports/screenshots/
        ls -l

    - name: Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports/
        token: ${{secrets.TEST12345}}
        clean: true
        
   
